language: cpp
dist: bionic

compiler:
  - clang
  - gcc

before_install:
 - git submodule init
 - git submodule update
 - python CodeXL/Scripts/FetchDependencies.py

install:
 - sudo apt-get install gcc-multilib g++-multilib libglu1-mesa-dev mesa-common-dev libgtk2.0-dev zlib1g-dev libx11-dev:i386 scons libjpeg9-dev libfltk1.3-dev libboost-all-dev

script:
 - cd Util/linux
 - ./buildCodeXLFullLinuxProjects
